angular.module("myapp")
	.config(config);
function config ($stateProvider,$urlRouterProvider) {
	$urlRouterProvider.otherwise("index");
	$stateProvider
		.state("index",{
			url:"/index",
			templateUrl:"html/min/index.min.html",
			controller:"index"
		})
		.state("fenglei",{
			url:"/fenglei",
			templateUrl:"html/min/fenglei.min.html",
			controller:"index"
		})
		.state("paihang",{
			url:"/paihang",
			templateUrl:"html/min/paihang.min.html",
			controller:"index"
		})
		.state("admain",{
			url:"/admain",
			templateUrl:"html/min/admain.min.html",
			controller:"index"
		})
		.state("shujia",{
			url:"/shujia",
			templateUrl:"html/min/shujia.min.html",
			controller:"shujia"
		})
		.state("nanpin",{
			url:"/nanpin",
			templateUrl:"html/min/nanpin.min.html",
			controller:"index"
		})
		.state("nvpin",{
			url:"/nvpin",
			templateUrl:"html/min/nvpin.min.html",
			controller:"index"
		})
		.state("wenxue",{
			url:"/wenxue",
			templateUrl:"html/min/wenxue.min.html",
			controller:"index"
		})
		.state("pianhao",{
			url:"/pianhao",
			templateUrl:"html/min/pianhao.min.html",
			controller:"index"
		})
		.state("yuepiaobang",{
			url:"/yuepiaobang",
			templateUrl:"html/min/yuepiaobang.min.html",
			controller:"index"
		})
		.state("denglu",{
			url:"/denglu",
			templateUrl:"html/min/denglu.min.html",
			controller:"login"
		})
		.state("user",{
			url:"/user",
			templateUrl:"html/min/user.min.html",
			controller:"index"
		})
		.state("shezhi",{
			url:"/shezhi",
			templateUrl:"html/min/shezhi.min.html",
			controller:"index"
		})
		.state("zhuche",{
			url:"/zhuche",
			templateUrl:"html/min/zhuche.min.html",
			controller:"zhuche"
		})
		.state("zhiliao",{
			url:"/zhiliao",
			templateUrl:"html/min/zhiliao.min.html",
			controller:"index"
		})
		.state("guanzhu",{
			url:"/guanzhu",
			templateUrl:"html/min/guanzhu.min.html",
			controller:"index"
		})
		.state("taolunqu",{
			url:"/taolunqu",
			templateUrl:"html/min/taolunqu.min.html",
			controller:"index"
		})
		.state("nicheng",{
			url:"/nicheng",
			templateUrl:"html/min/nicheng.min.html",
			controller:"index"
		})
		.state("shengri",{
			url:"/shengri",
			templateUrl:"html/min/shengri.min.html",
			controller:"index"
		})
		.state("diqu",{
			url:"/diqu",
			templateUrl:"html/min/diqu.min.html",
			controller:"index"
		})
		.state("jianjie",{
			url:"/jianjie",
			templateUrl:"html/min/jianjie.min.html",
			controller:"index"
		})
		.state("qiandao",{
			url:"/qiandao",
			templateUrl:"html/min/qiandao.min.html",
			controller:"index"
		})
		.state("xinshubang",{
			url:"/xinshubang",
			templateUrl:"html/min/xinshubang.min.html",
			controller:"index"
		})
		.state("reshoubang",{
			url:"/reshoubang",
			templateUrl:"html/min/reshoubang.min.html",
			controller:"index"
		})
		.state("fankui",{
			url:"/fankui",
			templateUrl:"html/min/fankui.min.html",
			controller:"index"
		})
		.state("mima",{
			url:"/mima",
			templateUrl:"html/min/mima.min.html",
			controller:"index"
		})
		.state("wangqi",{
			url:"/wangqi",
			templateUrl:"html/min/wangqi.min.html",
			controller:"index"
		})
		.state("jianglishuoming",{
			url:"/jianglishuoming",
			templateUrl:"html/min/jianglishuoming.min.html",
			controller:"index"
		})
		.state("mianfeibang",{
			url:"/mianfeibang",
			templateUrl:"html/min/mianfeibang.min.html",
			controller:"index"
		})
		.state("shouchang",{
			url:"/shouchang",
			templateUrl:"html/min/shouchang.min.html",
			controller:"index"
		})
}